OnlineShop/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OnlineShop.Areas.Identity.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

OnlineShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Models;
using OnlineShop.Models.Cart;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Models.ViewModels;
using OnlineShop.Models.BrainTree;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Mailjet.Client.Resources;
using Braintree;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using OnlineShop.Models.Message;

namespace OnlineShop.Controllers
{
    public class CartController : BaseController
    {
        private DBProjectContext _db;
        private readonly IAESSettings _aesSettings;

        private readonly IBraintreeService _braintreeService;

        public CartController(DBProjectContext db, IAESSettings aesSettings) : base(db)
        {
            _db = db;
            _aesSettings=aesSettings;
        }

    /*    public IActionResult Test()
        {
            var gateway = new BraintreeGateway
            {
                Environment = Braintree.Environment.SANDBOX,
                MerchantId= "q2h7nz489hsfj9r7",
                PublicKey= "9p7mxg8yjfg5vfgm",
                PrivateKey= "83f9cc7b1390a399bcc471aeaebfec5b"
            };

            TransactionRequest request = new TransactionRequest
            {
                Amount = 1000.00M,
                PaymentMethodNonce = "CreditCard",
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true
                }
            };

            Result<Transaction> result = gateway.Transaction.Sale(request);

            if (result.IsSuccess())
            {
                Transaction transaction = result.Target;
                Console.WriteLine("Success!: " + transaction.Id);
            }
            else if (result.Transaction != null)
            {
                Transaction transaction = result.Transaction;
                Console.WriteLine("Error processing transaction:");
                Console.WriteLine("  Status: " + transaction.Status);
                Console.WriteLine("  Code: " + transaction.ProcessorResponseCode);
                Console.WriteLine("  Text: " + transaction.ProcessorResponseText);
            }
            else
            {
                foreach (ValidationError error in result.Errors.DeepAll())
                {
                    Console.WriteLine("Attribute: " + error.Attribute);
                    Console.WriteLine("  Code: " + error.Code);
                    Console.WriteLine("  Message: " + error.Message);
                }
            }
            return View();
        }*/

        

    

        [HttpPost]
        public IActionResult AddToCart(int id, int quantity)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);             
                var cartItem = _db.CartItems.FirstOrDefault(c => c.ProductId == id && c.UserId == userId);

                var product = _db.Products.Find(id);
                if (cartItem != null)
                {
                    cartItem.Quantity += quantity;
                }
                else
                {
                    _db.CartItems.Add(new CartItem
                    {
                        ProductId = id,
                        ProductName= product.Name,
                        UserId = userId,
                        ProductPrice = product.IsOnSale ? product.Price * (100 - product.DiscountPercentage.Value) / 100 : product.Price,
                        Quantity = quantity,
                        Image= product.Image,
                    });
                }
                product.Amount-=quantity;
                _db.SaveChanges();
            }
            else
            {
                var cart = HttpContext.Session.GetObject<List<CartItem>>("cart") ?? new List<CartItem>();

                var product = _db.Products.Find(id);
                if (product == null)
                {
                    return NotFound();
                }

                var cartItem = cart.FirstOrDefault(c => c.ProductId == id);
                if (cartItem != null)
                {
                    cartItem.Quantity += quantity;
                }
                else
                {
                    cart.Add(new CartItem
                    {
                        ProductId = id,
                        ProductName = product.Name, 
                        ProductPrice = product.IsOnSale ? product.Price * (100 - product.DiscountPercentage.Value) / 100 : product.Price,      
                        Quantity = quantity,
                        Image = product.Image,
                    });
                }
                product.Amount-=quantity;
                _db.SaveChanges();
                HttpContext.Session.SetObject("cart", cart);
            }

            return RedirectToAction("DisplayCart");
        }

        [HttpPost]
        public IActionResult CheckAvailability(int productId, int quantity)
        {
            var product = _db.Products.Find(productId);
            if (product == null)
            {
                return NotFound();
            }

            if (quantity > product.Amount)
            {
                return Json(new { error = "Requested quantity is not available. Only " + product.Amount + " available." });
            }

            UpdateQuantity(productId, quantity);
            return Json(new { success = true });
        }

        [HttpPost]
        public IActionResult UpdateQuantity(int id, int quantity)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var cartItem = _db.CartItems.FirstOrDefault(c => c.ProductId == id && c.UserId == userId);

                var product = _db.Products.Find(id);
                if (quantity>cartItem.Quantity)
                {
                    var NewQuant = quantity-cartItem.Quantity;

                    cartItem.Quantity += NewQuant;
                    product.Amount-=NewQuant;
                }
                else
                {
                    var difQuant = cartItem.Quantity-quantity;
                    cartItem.Quantity = quantity;
                    product.Amount += difQuant;
                }
                
                _db.SaveChanges();
            }
            else
            {
                var cart = HttpContext.Session.GetObject<List<CartItem>>("cart") ?? new List<CartItem>();

                var product = _db.Products.Find(id);


                var cartItem = cart.FirstOrDefault(c => c.ProductId == id);
                if (quantity>cartItem.Quantity)
                {
                    var NewQuant = quantity-cartItem.Quantity;

                    cartItem.Quantity += NewQuant;
                    product.Amount-=NewQuant;
                }
                else
                {
                    var difQuant = cartItem.Quantity-quantity;
                    cartItem.Quantity = quantity;
                    product.Amount += difQuant;
                }
               
                _db.SaveChanges();
                HttpContext.Session.SetObject("cart", cart);
            }

            return RedirectToAction("DisplayCart");
        }


        public IActionResult DisplayCart()
        {
            List<CartItem> cart;

            if (User.Identity.IsAuthenticated)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                cart = _db.CartItems
                          .Where(c => c.UserId == userId)
                          .Include(c => c.Product) 
                          .ToList();
            }
            else
            {
                
                cart = HttpContext.Session.GetObject<List<CartItem>>("cart") ?? new List<CartItem>();
            }

            return View(cart);
        }

        

        [HttpPost]
        public IActionResult RemoveFromCart(int productId, int quantity)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var cartItem = _db.CartItems.FirstOrDefault(c => c.ProductId == productId && c.UserId == userId);

                if (cartItem != null)
                {
                    _db.CartItems.Remove(cartItem);
                }

                var product = _db.Products.Find(productId);
                if (product != null)
                {
                    product.Amount += quantity; 
                }

                _db.SaveChanges();
            }
            else
            {
                
                var cart = HttpContext.Session.GetObject<List<CartItem>>("cart") ?? new List<CartItem>();

                var cartItem = cart.FirstOrDefault(c => c.ProductId == productId);
                if (cartItem != null)
                {
                    cart.Remove(cartItem);
                    HttpContext.Session.SetObject("cart", cart); 
                }

                var product = _db.Products.Find(productId);
                if (product != null)
                {
                    product.Amount += quantity; 
                }

                _db.SaveChanges();
            }

            return RedirectToAction("DisplayCart");
        }

        [HttpPost]
        public IActionResult Checkout(CheckoutViewModel model, string selectedCardId,decimal PracentofDisc)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var user = _db.Users.FirstOrDefault(u => u.Id == userId); 
                var cartItems = _db.CartItems.Where(c => c.UserId == userId).ToList();
                var cardinfo = _db.CreditCards

OnlineShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Models;
using OnlineShop.Models.Message;
using System.Security.Claims;
using System.Threading.Tasks;

namespace OnlineShop.Controllers
{
	public class ProductController : BaseController
    {
		private readonly DBProjectContext _context;

		public ProductController(DBProjectContext context) : base(context)
        {
			_context = context;
		}

		public async Task<IActionResult> Index()
		{
			var products = await _context.Products.Include(p => p.Category).ToListAsync();
			return View(products);
		}

        public IActionResult AddProduct()
        {
            ViewBag.Categories = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddProduct(Product product)
        {
            ModelState.Remove("Category");
            ModelState.Remove("CartItems");
            if (ModelState.IsValid)
            {
                _context.Products.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categories = new SelectList(await _context.Categories.ToListAsync(), "Id", "Name");
            return View(product);
        }


        [HttpPost]
        [Authorize]
        public ActionResult RequestNotification2(int productId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var notification = new ProductNotification { ProductId = productId, UserId = userId };
            _context.ProductNotifications.Add(notification);
            _context.SaveChanges();

            return Json(new { success = true });
        }

        [HttpPost]
        [Authorize] 
        public ActionResult RequestNotification(int productId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    
            var existingNotification = _context.ProductNotifications.FirstOrDefault(n => n.ProductId == productId && n.UserId == userId);
            if (existingNotification != null)
            {
                return Json(new { success = false, message = "You have already requested a notification for this product." });
            }

            var notification = new ProductNotification { ProductId = productId, UserId = userId };
            _context.ProductNotifications.Add(notification);
            _context.SaveChanges();

            return Json(new { success = true });
        }


        public async Task<IActionResult> Edit(int id)
		{
			var product = await _context.Products.FindAsync(id);
			if (product == null)
			{
				return NotFound();
			}
			ViewBag.Categories = new SelectList(await _context.Categories.ToListAsync(), "Id", "Name");
			return View(product);
		}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit1(Product product)
        {
            ModelState.Remove("Category");
            if (ModelState.IsValid)
            {
                _context.Update(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categories = new SelectList(await _context.Categories.ToListAsync(), "Id", "Name");
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product product)
        {
            ModelState.Remove("Category");
            if (ModelState.IsValid)
            {
                _context.Update(product);
                await _context.SaveChangesAsync();

                if (product.Amount > 0) 
                {
                    var notifications = _context.ProductNotifications.Where(n => n.ProductId == product.Id).ToList();
                    foreach (var notification in notifications)
                    {

                        var message = new MessageInbox
                        {
                            Subject = "Product Restocked: " + product.Name,
                            Content = "The product '" + product.Name + "' you were interested in is now back in stock!",
                            ReceivedTime = DateTime.Now,
                            IsRead = false,
                            UserId = notification.UserId 
                        };
                        _context.ProductNotifications.Remove(notification);
                        _context.messages.Add(message);
                    }
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categories = new SelectList(await _context.Categories.ToListAsync(), "Id", "Name");
            return View(product);
        }


        public async Task<IActionResult> Delete(int id)
		{
			var product = await _context.Products.FindAsync(id);
			if (product != null)
			{
				_context.Products.Remove(product);
				await _context.SaveChangesAsync();
			}
			return RedirectToAction(nameof(Index));
		}


	}
}

OnlineShop/Views/Shared/AccessDenied.cshtml
@model ErrorViewModel

@{
    ViewData["Title"] = "Access denied";
}
<link rel="stylesheet" href="~/OnlineShop.styles.css" asp-append-version="true" />

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
    body {
        background-color: black;
        color: white;
    }

    h1 {
        color: red;
    }

    h6 {
        color: red;
        text-decoration: underline;
    }
</style>


    <title>Access Denied</title>

    <div class="w3-display-middle">
        <h1 class="w3-jumbo w3-animate-top w3-center"><code>Access Denied</code></h1>
        <h3 class="w3-center w3-animate-right">You dont have permission to view this site.</h3>
        <h3 class="w3-center w3-animate-zoom">🚫🚫🚫🚫</h3>
    </div>

OnlineShop/Views/Shared/_IndividualProductCard.cshtml
@model OnlineShop.Models.Product

<div class="product-container" style="background-image: url('@Model.Image');">
    <div class="overlay">
        <div class="items"></div>
        <div class="items head">
            <p>@Model.Name</p>
            <hr>
        </div>
        <div class="items description">
            <p>@Model.Description</p>
        </div>
        <div class="items price">
            @if (Model.IsOnSale)
            {
                <p class="old">ILS @Model.Price</p>
                <p class="new">ILS @(Model.Price - (Model.Price * Model.DiscountPercentage / 100))</p>
            }
            else
            {
                <p class="new">ILS @Model.Price</p>
            }
        </div>
        @if (Model.Amount > 0)
        {
            <div class="items quantity">
                <input type="number" id="quantity-@Model.Id" value="1" min="1" max="@Model.Amount">
            </div>
            <div class="items actions">
                <button class="btn btn-add-to-cart" onclick="handleAction(@Model.Id, 'add')"><i class="fa fa-shopping-cart"></i><span>Add to Cart</span></button>
                <button class="btn btn-buy" onclick="handleAction(@Model.Id, 'buy')"><i class="fa fa-bolt"></i><span>Buy Now</span></button>
            </div>
        }
        else
        {
            <div class="items out-of-stock">
                <p>Out of Stock</p>
                @if (User.Identity.IsAuthenticated)
                {
                    <button class="btn btn-notify" onclick="notifyMe(@Model.Id)">Notify Me</button>
                }
                else
                {
                    <button class="btn btn-notify" onclick="alert('Only registered users can use the Notify Me feature. Please log in or register.');">Notify Me</button>
                }
            </div>


            <p class="notify-message-@Model.Id" style="display: none;">You will be notified when the product is available.</p>


        }
    </div>

    <script>
        function notifyMe(productId) {
            $.post('@Url.Action("RequestNotification", "Product")', { productId: productId }, function (response) {
                if (response.success) {
                    alert('You will be notified when the product is available.');
                    $('.notify-message').show();
                } else {
                    alert(response.message);
                }
            });
        }


        function showNotifyInput(button) {
            var notifyInput = button.closest('.items').nextElementSibling;
            notifyInput.style.display = 'block';
        }

        function sendNotification(event, form, productId) {
            event.preventDefault();
            var email = form.querySelector('input[name="email"]').value;

            $.post('@Url.Action("RequestNotification", "Product")', { productId: productId, email: email }, function () {
                form.style.display = 'none';
                form.nextElementSibling.style.display = 'block';
            });
        }


        function handleAction(productId, action) {
            var quantityInput = document.getElementById('quantity-' + productId);
            var quantity = parseInt(quantityInput.value);
            var maxQuantity = parseInt(quantityInput.max);

            if (quantity > maxQuantity) {
                alert('Not enough in stock.');
            } else {
                if (action === 'add') {
                    $.post('@Url.Action("AddToCart", "Cart")', { id: productId, quantity: quantity }, function () {
                        alert('Added ' + quantity + ' item(s) to cart.');
                        location.reload();
                    });
                } else if (action === 'buy') {

                    $.post('@Url.Action("AddToCart", "Cart")', { id: productId, quantity: quantity }, function () {
                        window.location.href = '@Url.Action("DisplayCart", "Cart")'; 
                    });
                }
            }
        }
    </script>

</div>

OnlineShop/Views/Shared/_Layout-original.cshtml
@{
    //<partial name="_LoginPartial" />
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - OnlineShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

</head>

<style>
    :root {
        --pink: #e84393;
    }

    
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        outline: none;
        border: none;
        text-decoration: none;
        text-transform: capitalize;
        transition: .2s linear;
    }

    html {
        font-size: 62.5%;
        scroll-behavior: smooth;
        scroll-padding-top: 6rem;
        overflow-x: hidden;
    }

    section {
        padding: 2rem 9%;
    }

    .heading {
        text-align: center;
        font-size: 4rem;
        color: #333;
        padding: 1rem;
        margin: 2rem 0;
        background: rgba(255, 51, 153,.05);
    }

    .heading span {
        color: var(--pink);
    }

    .btn {
        display: inline-block;
        margin-top: 1rem;
        border-radius: 5rem;
        
        color: #fff;
        
        cursor: pointer;
        font-size: 1.7rem;
    }

    .btn:hover {
        background: var(--pink);
    }

    header {
        top: 0;
        left: 0;
        right: 0;
        background: #fff;
        padding: 1rem 9%; 
        display: flex;
        align-items: center;
        justify-content: space-between;
        z-index: 1000;
        box-shadow: 0 .5rem 1rem rgba(0,0,0,.1);
    }


        header .navbar-brand {
            font-size: 3rem;
            color: #333;
            font-weight: bolder;
        }

        header .navbar-brand span {
            color: var(--pink);
        }

    header .navbar a {
        font-size: 2rem;
        padding: 0 1.5rem;
        color: #666;
    }

    header .navbar a:hover {
        color: var(--pink);
    }

    header .icons a {
        font-size: 2.5rem;
        color: #333;
        margin-left: 1.5rem;
    }

    header .icons a:hover {
        color: var(--pink);
    }

    header #toggler {
        display: none;
    }

    header .fa-bars {
        font-size: 3rem;
        color: #333;
        border-radius: .5rem;
        padding: .5rem 1.5rem;
        cursor: pointer;
        border: .1rem solid rgba(0,0,0,.3);
        display: none;
    }

    .chatbot-icon {
        position: fixed;
        bottom: 20px;
        right: 20px;
        font-size: 3em;
        cursor: pointer;
        z-index: 1000;
    }
    .home {
        display: flex;
        align-items: center;
        min-height: 100vh;
        background: url(../images/home-bgs.jpg) no-repeat;
        background-size: cover;
        background-position: center;
    }

    .home .content {
        max-width: 50rem;
    }

    .home .content h3 {
        font-size: 6rem;
        color: #333;
    }

    .home .content span {
        font-size: 3.5rem;
        color: var(--pink);
        padding: 1rem 0;
        line-height: 1.5;
    }

    .home .content p {
        font-size: 1.5rem;
        color: #999;
        padding: 1rem 0;
        line-height: 1.5;
    }



        .form-container {
            display: flex;
            justify-content: center;
            margin-top: 8rem;

            .products-grid {
                display: flex;
                flex-wrap: wrap;
            }

</style>
<i class="fas fa-robot chatbot-icon" style="color: #74C0FC;" id="chatbotIcon"></i>

<body>   
    <header>

        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShop</a>
       
        
        <nav class="navbar">
            <a href="/">home</a>

            <a href="/Home/About">about</a>

            @if (User.IsInRole("Admin") || User.IsInRole("Advanced"))

            {
                <div class="dropdown" id="adminDropdown">
                    <a class="dropdown-toggle" role="button" id="adminDropdownToggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Admin Management
                    </a>
                    <div class="dropdown-menu" aria-labelledby="adminDropdownToggle">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="dropdown-item" href="/Identity/Admin/Dashboard">Dashboard</a>
                        }
                        
                        <a class="dropdown-item" href="/Category">Categories Manage</a>
                        <a class="dropdown-item" href="/Product">Products Manage</a>
                        <a class="dropdown-item" href="/order">Orders</a>
                        

                        @if (User.IsInRole("Admin"))
                        {
                            <a class="dropdown-item" href="/promocode">Promo Codes</a>
                        }
                    </div>
                </div>
            }

            @if (User.IsInRole("Regular") || User.IsInRole("Advanced") || User.IsInRole("Admin"))
            {
                 <a href="/order/UserOrders">My Orders</a>
            }
               

          
         
            


           
        </nav>
        
        <partial name="_LoginPartial" />
        <div class="icons">
            <a href="/CART/DisplayCart" class="fas fa-shopping-cart" style="position: relative;">
            @if (ViewBag.CartProducts  > 0)
            {
                <span style="background-color: red; color: white; border-radius: 50%; padding: 1px 3px; font-size: 10px; position: absolute; top: -5px; right: -5px;">
                    @ViewBag.CartProducts
                </span>
            }
            </a>
            <a href="/Identity/Account/Manage" class="fas fa-user"></a>
            
        </div>
        
    </header>


    <div class="container">

        @RenderBody()

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        $(document).ready(function () {
            $('#adminDropdown').hover(function () {
                $(this).addClass('show');
                $(this).find('.dropdown-menu').addClass('show');
            }, function () {
                $(this).removeClass('show');
                $(this).find('.dropdown-menu').removeClass('show');
            });
            $('#chatbotIcon').click(function () {
                window.location.href = '/Chatbot/Chat/'; 
            });
        });
    </script>

    

</body>


</html>