OnlineShop/Models/Message/MessageInbox.cs
namespace OnlineShop.Models.Message
{
    public class MessageInbox
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public DateTime ReceivedTime { get; set; }
        public bool IsRead { get; set; }
        public virtual User User { get; set; }
        public string UserId { get; set; } 

    }
}

OnlineShop/Models/Message/ProductNotification.cs
namespace OnlineShop.Models.Message
{
    public class ProductNotification
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public bool Notified { get; set; } = false;
        public string UserId { get; set; }
        public virtual User User { get; set; }

    }

}

OnlineShop/Controllers/MessageController.cs
using Mailjet.Client.Resources;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Models;
using OnlineShop.Models.Message;
using System.Security.Claims;
namespace OnlineShop.Controllers
{
    public class MessageController : BaseController
    {
        private readonly DBProjectContext _context;
        public MessageController(DBProjectContext context): base(context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            var ms =  _context.messages.ToList();
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var messages = _context.messages.Where(m => m.UserId == userId).ToList(); 
                return View(messages);
            }
            return View("AccessDenied");

        }

        public ActionResult MarkAsRead(int id)
        {
            var message = _context.messages.Find(id);
            if (message != null)
            {
                message.IsRead = true;
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteMessage(int id)
        {
            var message = await _context.messages.FindAsync(id);
            if (message == null)
            {
                return NotFound();
            }

            _context.messages.Remove(message);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index"); 
        }

    }
}

OnlineShop/Views/Message/Index.cshtml
@model IEnumerable<OnlineShop.Models.Message.MessageInbox>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="~/OnlineShop.styles.css" asp-append-version="true" />

<style>
    h2 {
        margin-bottom: 20px;
    }

    .table-primary {
        font-weight: bold;
    }
</style>
<h2>Inbox</h2>

<table class="table table-hover">
    <thead class="thead-light">
        <tr>
            <th>Subject</th>
            <th>Content</th>
            <th>Received</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var message in Model)
        {
            <tr class="@(!message.IsRead ? "table-primary" : "")">
                <td>@message.Subject</td>
                <td>@message.Content</td>
                <td>@message.ReceivedTime.ToString("g")</td>
                <td>
                    @if (!message.IsRead)
                    {
                        <a href="@Url.Action("MarkAsRead", "Message", new { id = message.Id })" class="btn btn-sm btn-success">Mark as Read</a>
                    }
                    <a href="@Url.Action("DeleteMessage", "Message", new { id = message.Id })" class="btn btn-sm btn-danger">Delete</a>
                </td>

            </tr>
        }
    </tbody>
</table>