OnlineShop/Models/Cart/PromoCode.cs
namespace OnlineShop.Models.Cart
{
    public class PromoCode
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public decimal DiscountPercentage { get; set; }
        public DateTime ExpiryDate { get; set; }
        public bool IsActive { get; set; }
    }
}

OnlineShop/Controllers/PromoCodeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Models;
using OnlineShop.Models.Cart;

namespace OnlineShop.Controllers
{
    public class PromoCodeController : BaseController
    {
        private readonly DBProjectContext _context;

        public PromoCodeController(DBProjectContext context) : base(context)
        {
            _context = context;
        }
        public ActionResult Index()
        {
            var promoCodes = _context.PromoCodes.ToList();
            return View(promoCodes);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PromoCode promoCode)
        {
            if (ModelState.IsValid)
            {
                _context.PromoCodes.Add(promoCode);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(promoCode);
        }

        public ActionResult Delete(int id)
        {
            var promoCode = _context.PromoCodes.Find(id);
            if (promoCode == null)
            {
                return View();
            }
            return View(promoCode);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var promoCode = _context.PromoCodes.Find(id);
            _context.PromoCodes.Remove(promoCode);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ToggleActive(int id)
        {
            var promoCode = _context.PromoCodes.Find(id);
            if (promoCode == null)
            {
                return View();
            }

            promoCode.IsActive = !promoCode.IsActive; 
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        

    }
}

OnlineShop/Views/PromoCode/Index.cshtml
@model IEnumerable<OnlineShop.Models.Cart.PromoCode>

<h2>Promo Codes</h2>

<table class="table">
    <thead>
        <tr>
            <th>Code</th>
            <th>Discount Percentage</th>
            <th>Expiry Date</th>
            <th>Active</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var promo in Model)
        {
            <tr>
                <td>@promo.Code</td>
                <td>@promo.DiscountPercentage</td>
                <td>@promo.ExpiryDate.ToString("d")</td>
                <td>@promo.IsActive</td>
                <td>
                    <a href="@Url.Action("Edit", "PromoCode", new { id = promo.Id })">Edit</a> |
                    <a href="@Url.Action("Delete", "PromoCode", new { id = promo.Id })">Delete</a> |
                    <a href="@Url.Action("ToggleActive", "PromoCode", new { id = promo.Id })">
                        @(promo.IsActive ? "Deactivate" : "Activate")
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a href="@Url.Action("Create", "PromoCode")" class="btn btn-primary">Create New Promo Code</a>

OnlineShop/Views/PromoCode/create.cshtml
@model OnlineShop.Models.Cart.PromoCode

<h2>Create Promo Code</h2>

@using (Html.BeginForm("Create", "PromoCode", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.Code)
        @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DiscountPercentage)
        @Html.TextBoxFor(model => model.DiscountPercentage, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ExpiryDate)
        @Html.TextBoxFor(model => model.ExpiryDate, new { @class = "form-control", type = "date" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IsActive)
        @Html.CheckBoxFor(model => model.IsActive)
    </div>
    <button type="submit" class="btn btn-success">Create</button>
}

<a href="@Url.Action("Index", "PromoCode")" class="btn btn-secondary">Back to List</a>

OnlineShop/Views/PromoCode/delete.cshtml
@model OnlineShop.Models.Cart.PromoCode

<h2>Delete Promo Code</h2>

<h3>Are you sure you want to delete this promo code?</h3>
<div>
    <h4>Promo Code</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Code</dt>
        <dd>@Html.DisplayFor(model => model.Code)</dd>
        <dt>Discount Percentage</dt>
        <dd>@Html.DisplayFor(model => model.DiscountPercentage)</dd>
        <dt>Expiry Date</dt>
        <dd>@Html.DisplayFor(model => model.ExpiryDate)</dd>
        <dt>Active</dt>
        <dd>@Html.DisplayFor(model => model.IsActive)</dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>